name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'

    - name: Build Linux
      run: GOOS=linux GOARCH=amd64 go build -v -o scrubber cmd/cli.go

    - name: Upload Linux Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: scrubber
        path: scrubber

    - name: Upload Linux Runner Artifact
      uses: actions/upload-artifact@v4
      with:
        name: runner.sh
        path: scripts/runner.sh

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -v -o scrubber.exe cmd/cli.go

    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: scrubber.exe
        path: scrubber.exe

    - name: Upload Windows Script Artifact
      uses: actions/upload-artifact@v4
      with:
        name: runner.ps1
        path: scripts/runner.ps1 
